# Generated by Django 5.2.7 on 2025-12-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
    ]
