# Generated by Django 5.2.7 on 2025-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_add_slug_to_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
